mod test_arrow;
mod test_builder;
mod test_data;
mod test_helpers;
// mod test_dimensional;
mod test_clustering;
mod test_graph_factory;
mod test_laplacian;
mod test_laplacian_unnormalised;
mod test_querying_proj;
mod test_reduction;
mod test_taumode;
